### ISSUE TITLE
flask_simpleldap.LDAPException: Invalid credentials

### ISSUE THREAD

**Issue by ltpitt** [admiralobvious/flask-simpleldap#50]
Hello there,

I have just installed flask and flask-simpleldap on a freshly created a Ubuntu Virtual Box.
I also installed a fresh Windows2012 Virtual Box and they can perfectly communicate (I ping the Ubuntu from Windows and I also open successfully the webapp from Internet Explorer).

I've tweaked the example script:
```
from flask import Flask, g, request, session, redirect, url_for
from flask_simpleldap import LDAP

app = Flask(__name__)
app.secret_key = 'dev key'
app.debug = True

#app.config['LDAP_USE_SSL'] = True
app.config['LDAP_HOST'] = 'my-dc-server'
app.config['LDAP_BASE_DN'] = 'OU=-my-ou,dc=my,dc=domain,dc=com'
app.config['LDAP_USERNAME'] = 'CN=my-domain-admin-working-user,OU=my-ou,DC=my,DC=domain,DC=com'
app.config['LDAP_PASSWORD'] = 'my-domain-admin-working-password'

ldap = LDAP(app)

@app.route('/')
@ldap.basic_auth_required
def index():
    return 'Welcome, {0}!'.format(g.ldap_username)

if __name__ == '__main__':
    app.debug = True
    app.run(host='0.0.0.0', port=8000)
```

I insert the right user data (double checked and tested) and all I get is:
```
Traceback (most recent call last):
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask_simpleldap/__init__.py", line 386, in wrapped
    if not self.bind_user(req_username, req_password):
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask_simpleldap/__init__.py", line 152, in bind_user
    user_dn = self.get_object_details(user=username, dn_only=True)
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask_simpleldap/__init__.py", line 185, in get_object_details
    conn = self.bind
  File "/home/ubuntu/ipcatalogue_env/lib/python3.5/site-packages/flask_simpleldap/__init__.py", line 129, in bind
    raise LDAPException(self.error(e.args))
flask_simpleldap.LDAPException: Invalid credentials
```

Is flask-simpleldap still working today with Python 3.5 and Windows 2012?

**Comment by chrispruitt** [comment]
I am having the same issue. Were you able to solve it?

**Comment by chrispruitt** [comment]
I actually just got it working. My LDAP_BASENAME was messed up a bit, but this is what I have that finally got everything working. Obvisously I have mocked my usernames, passwords, and identifiers but hope this helps! 

`app.config['LDAP_HOST'] = 'myldaphost.com'
app.config['LDAP_SCHEMA'] = 'ldaps'
app.config['LDAP_PORT'] = 636
app.config['LDAP_BASE_DN'] = 'ou=Users,o=5342Dkfhsd32kjh234,dc=myldaphost,dc=com'
app.config['LDAP_USERNAME'] = 'uid=ldapbinduser,ou=Users,o=5342Dkfhsd32kjh234,dc=myldaphost,dc=com'
app.config['LDAP_PASSWORD'] = 'mypassword'
app.config['LDAP_USER_OBJECT_FILTER'] = '(uid=%s)'
app.config['LDAP_OPENLDAP'] = True`

**Comment by ltpitt** [comment]
@chrispruitt 
Oh my!
You deserve a medal, sir!
Can't wait to test it...

Deeply thanks 🕺
