### ISSUE TITLE
AttributeError in bind_user with invalid username

### ISSUE THREAD

**Issue by Nothing4You** [admiralobvious/flask-simpleldap#61]
When passing an invalid username I'm getting an exception rather than `None`:

```
Traceback (most recent call last):
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/$USER/dev/myproject/myproject.py", line 98, in login
    test = ldap.bind_user(user, passwd)
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 147, in bind_user
    user_dn = self.get_object_details(user=username, dn_only=True)
  File "/Users/$USER/.local/share/virtualenvs/myproject-A47Vo0O9/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 197, in get_object_details
    for k, v in list(records[0][1].items()):
AttributeError: 'list' object has no attribute 'items'
```

**Comment by admiralobvious** [comment]
Fixed in v1.3.0
